FROM 111664719423.dkr.ecr.us-east-1.amazonaws.com/base:latest@sha256:0810d30f5aa8f2446d60ed7f03661a09c5745460d021df729710b60cea6e75cd
#ARG REVISION
#ARG SOURCE
#LABEL org.opencontainers.image.revision=$REVISION
#LABEL org.opencontainers.image.source=$SOURCE
CMD ["cat", "{:version 15}"]

