FROM 111664719423.dkr.ecr.us-east-1.amazonaws.com/base:latest@sha256:00fda1a4c701974ef0c681d30e25024dd6bdf31433e873260bdf2ecf1173fd07
#ARG REVISION
#ARG SOURCE
#LABEL org.opencontainers.image.revision=$REVISION
#LABEL org.opencontainers.image.source=$SOURCE
CMD ["cat", "{:version 11}"]

