FROM 111664719423.dkr.ecr.us-east-1.amazonaws.com/base:latest@sha256:773f3d835f4da4b3f58d97bbb11a13a6c9ecb543606cabef02fec61ffd62ff64
#ARG REVISION
#ARG SOURCE
#LABEL org.opencontainers.image.revision=$REVISION
#LABEL org.opencontainers.image.source=$SOURCE
CMD ["cat", "{:version 14}"]

